// Generated by scripts/sync-env.mjs (prod).
// Do not edit by hand — set env vars or .env.local instead.
export const environment = {
  "production": true,
  "supabaseUrl": "https://fpqolqiivzokwpmymqsr.supabase.co",
  "supabaseAnonKey": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwcW9scWlpdnpva3dwbXltcXNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA5MTEyMTUsImV4cCI6MjA5NjQ4NzIxNX0.WeeDqlVPLPKtd2XPGtQeuPaIdQqhIrEZhWraW_SnnL4",
  "apiBaseUrl": "https://api.kolss.eu",
  "siteUrl": "http://localhost:3000",
  "siteUrlPublic": "https://crm.kolss.eu"
};
