import type { CrmOffice, MockEmployee, MockLead } from './crm-mock.types';

export const CRM_MOCK_NOW = '2026-07-07T09:00:00.000Z';
export const CRM_MOCK_ACTOR_ID = 'emp-super-admin';

export const CRM_MOCK_OFFICES: readonly CrmOffice[] = [
  { id: 'kyiv', code: 'kyiv', nameUk: 'Київ', namePl: 'Kijów' },
  { id: 'warsaw', code: 'warsaw', nameUk: 'Варшава', namePl: 'Warszawa' },
];

export const CRM_MOCK_EMPLOYEES: readonly MockEmployee[] = [
  {
    id: CRM_MOCK_ACTOR_ID,
    displayName: 'Олена Коваль',
    email: 'olena.koval@kolss.com',
    role: 'super_admin',
    officeIds: ['kyiv', 'warsaw'],
    status: 'active',
    locale: 'uk',
    createdAt: '2025-02-03T10:00:00.000Z',
    lastActiveAt: '2026-07-07T08:44:00.000Z',
  },
  {
    id: 'emp-curator',
    displayName: 'Марек Войцех',
    email: 'marek.wojciech@kolss.com',
    role: 'curator',
    officeIds: ['kyiv', 'warsaw'],
    status: 'active',
    locale: 'pl',
    createdAt: '2025-04-15T09:30:00.000Z',
    lastActiveAt: '2026-07-07T08:12:00.000Z',
  },
  {
    id: 'emp-office-admin-kyiv',
    displayName: 'Ірина Шевченко',
    email: 'iryna.shevchenko@kolss.com',
    role: 'office_admin',
    officeIds: ['kyiv'],
    status: 'active',
    locale: 'uk',
    createdAt: '2025-06-01T12:15:00.000Z',
    lastActiveAt: '2026-07-06T16:50:00.000Z',
  },
  {
    id: 'emp-kyiv-1',
    displayName: 'Данило Мороз',
    email: 'danylo.moroz@kolss.com',
    role: 'office_member',
    officeIds: ['kyiv'],
    status: 'active',
    locale: 'uk',
    createdAt: '2025-09-10T08:30:00.000Z',
    lastActiveAt: '2026-07-07T07:25:00.000Z',
  },
  {
    id: 'emp-kyiv-2',
    displayName: 'Софія Литвин',
    email: 'sofia.lytvyn@kolss.com',
    role: 'office_member',
    officeIds: ['kyiv'],
    status: 'active',
    locale: 'uk',
    createdAt: '2025-11-02T14:00:00.000Z',
    lastActiveAt: '2026-07-05T11:20:00.000Z',
  },
  {
    id: 'emp-kyiv-3',
    displayName: 'Андрій Павленко',
    email: 'andrii.pavlenko@kolss.com',
    role: 'office_member',
    officeIds: ['kyiv'],
    status: 'inactive',
    locale: 'uk',
    createdAt: '2026-01-12T09:45:00.000Z',
    lastActiveAt: '2026-06-28T13:10:00.000Z',
  },
  {
    id: 'emp-warsaw-1',
    displayName: 'Julia Nowak',
    email: 'julia.nowak@kolss.com',
    role: 'office_member',
    officeIds: ['warsaw'],
    status: 'active',
    locale: 'pl',
    createdAt: '2025-08-19T10:40:00.000Z',
    lastActiveAt: '2026-07-07T08:05:00.000Z',
  },
  {
    id: 'emp-warsaw-2',
    displayName: 'Piotr Zielinski',
    email: 'piotr.zielinski@kolss.com',
    role: 'office_member',
    officeIds: ['warsaw'],
    status: 'active',
    locale: 'pl',
    createdAt: '2025-10-24T13:20:00.000Z',
    lastActiveAt: '2026-07-06T15:35:00.000Z',
  },
  {
    id: 'emp-warsaw-3',
    displayName: 'Natalia Kaczmarek',
    email: 'natalia.kaczmarek@kolss.com',
    role: 'office_member',
    officeIds: ['warsaw'],
    status: 'active',
    locale: 'en',
    createdAt: '2026-02-08T11:15:00.000Z',
    lastActiveAt: '2026-07-04T09:50:00.000Z',
  },
];

export const CRM_MOCK_LEADS: readonly MockLead[] = [
  {
    id: 'lead-1001',
    name: 'Марина Гончар',
    phone: '+380 67 214 88 19',
    email: 'maryna.honchar@example.com',
    leadStatus: 'new',
    workflowStatus: 'new',
    officeCode: 'kyiv',
    source: 'website',
    sourceCreatedAt: '2026-07-06T11:24:00.000Z',
    initialMessage: 'Потрібна консультація щодо кухні для квартири у Києві.',
    cityRegion: 'Київ, Печерськ',
    productInterest: 'Кухня під замовлення',
    estimatedBudget: 18000,
    assignedToId: null,
    firstManagerId: null,
    firstCall: null,
    visit: null,
    close: null,
    contract: null,
    callbackDueAt: '2026-07-07T12:00:00.000Z',
    lastComment: null,
    lastActivityAt: '2026-07-06T11:24:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1001-created',
        type: 'created',
        title: 'Заявка створена',
        body: 'Клієнт залишив заявку на сайті.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-07-06T11:24:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1002',
    name: 'Anna Kowalska',
    phone: '+48 501 223 118',
    email: 'anna.kowalska@example.com',
    leadStatus: 'in_progress',
    workflowStatus: 'taken',
    officeCode: 'warsaw',
    source: 'facebook',
    sourceCreatedAt: '2026-07-05T09:05:00.000Z',
    initialMessage: 'Interesuje mnie garderoba do mieszkania w Warszawie.',
    cityRegion: 'Warszawa, Mokotow',
    productInterest: 'Гардеробна',
    estimatedBudget: 12500,
    assignedToId: 'emp-warsaw-1',
    firstManagerId: 'emp-warsaw-1',
    firstCall: null,
    visit: null,
    close: null,
    contract: null,
    callbackDueAt: '2026-07-07T10:30:00.000Z',
    lastComment: 'Клієнт просив передзвонити після 10:00.',
    lastActivityAt: '2026-07-05T10:14:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1002-created',
        type: 'created',
        title: 'Заявка з Facebook',
        body: 'Форма з контактом і коротким описом гардеробної.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-07-05T09:05:00.000Z',
      },
      {
        id: 'evt-1002-taken',
        type: 'taken',
        title: 'Лід взято в роботу',
        body: 'Julia Nowak першою взяла заявку.',
        actorId: 'emp-warsaw-1',
        occurredAt: '2026-07-05T10:14:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1003',
    name: 'Олександр Бойко',
    phone: '+380 93 118 44 02',
    email: null,
    leadStatus: 'in_progress',
    workflowStatus: 'first_call_done',
    officeCode: 'kyiv',
    source: 'office',
    sourceCreatedAt: '2026-07-01T15:42:00.000Z',
    initialMessage: 'Ручна заявка після дзвінка в салон.',
    cityRegion: 'Бровари',
    productInterest: 'Шафа-купе',
    estimatedBudget: 9200,
    assignedToId: 'emp-kyiv-1',
    firstManagerId: 'emp-kyiv-1',
    firstCall: {
      date: '2026-07-01T16:10:00.000Z',
      result: 'Потреба підтверджена',
      comment: 'Клієнт планує замір після вихідних.',
    },
    visit: null,
    close: null,
    contract: null,
    callbackDueAt: '2026-07-08T08:00:00.000Z',
    lastComment: 'Підготувати приклади фасадів.',
    lastActivityAt: '2026-07-01T16:10:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1003-created',
        type: 'created',
        title: 'Ручна заявка',
        body: 'Менеджер створив заявку після вхідного дзвінка.',
        actorId: 'emp-kyiv-1',
        occurredAt: '2026-07-01T15:42:00.000Z',
      },
      {
        id: 'evt-1003-call',
        type: 'first_call',
        title: 'Перший дзвінок зафіксовано',
        body: 'Потреба підтверджена. Клієнт планує замір після вихідних.',
        actorId: 'emp-kyiv-1',
        occurredAt: '2026-07-01T16:10:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1004',
    name: 'Marta Wisniewska',
    phone: '+48 602 771 009',
    email: 'marta.w@example.com',
    leadStatus: 'in_progress',
    workflowStatus: 'visit_scheduled',
    officeCode: 'warsaw',
    source: 'website',
    sourceCreatedAt: '2026-06-28T12:18:00.000Z',
    initialMessage: 'Chce umowic spotkanie w salonie w sprawie kuchni.',
    cityRegion: 'Warszawa, Wola',
    productInterest: 'Кухня + острів',
    estimatedBudget: 24000,
    assignedToId: 'emp-warsaw-2',
    firstManagerId: 'emp-warsaw-2',
    firstCall: {
      date: '2026-06-28T13:05:00.000Z',
      result: 'Заплановано візит',
      comment: 'Клієнтка прийде з планом квартири.',
    },
    visit: {
      status: 'scheduled',
      scheduledAt: '2026-07-09T13:00:00.000Z',
      comment: 'Показати рішення з островом.',
    },
    close: null,
    contract: null,
    callbackDueAt: null,
    lastComment: 'Очікуємо в салоні 9 липня.',
    lastActivityAt: '2026-06-28T13:20:00.000Z',
    attachments: [
      {
        id: 'att-1004-plan',
        name: 'plan-mieszkania.pdf',
        sizeLabel: '1.8 MB',
        addedAt: '2026-06-28T13:18:00.000Z',
      },
    ],
    events: [
      {
        id: 'evt-1004-created',
        type: 'created',
        title: 'Заявка з сайту',
        body: 'Клієнтка описала кухню з островом.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-06-28T12:18:00.000Z',
      },
      {
        id: 'evt-1004-visit',
        type: 'visit_scheduled',
        title: 'Візит заплановано',
        body: '9 липня, 13:00. Показати рішення з островом.',
        actorId: 'emp-warsaw-2',
        occurredAt: '2026-06-28T13:20:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1005',
    name: 'Ігор Мельник',
    phone: '+380 50 411 31 44',
    email: 'ihor.melnyk@example.com',
    leadStatus: 'in_progress',
    workflowStatus: 'visit_rescheduled',
    officeCode: 'kyiv',
    source: 'facebook',
    sourceCreatedAt: '2026-06-20T08:33:00.000Z',
    initialMessage: 'Цікавить гардеробна для будинку під Києвом.',
    cityRegion: 'Ірпінь',
    productInterest: 'Гардеробна кімната',
    estimatedBudget: 15000,
    assignedToId: 'emp-kyiv-2',
    firstManagerId: 'emp-kyiv-2',
    firstCall: {
      date: '2026-06-20T09:00:00.000Z',
      result: 'Погоджено візит',
      comment: 'Потрібно подивитися зразки наповнення.',
    },
    visit: {
      status: 'rescheduled',
      scheduledAt: '2026-07-10T10:00:00.000Z',
      comment: 'Перенесли через відрядження клієнта.',
    },
    close: null,
    contract: null,
    callbackDueAt: null,
    lastComment: 'Перенесено на 10 липня.',
    lastActivityAt: '2026-07-02T12:30:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1005-created',
        type: 'created',
        title: 'Заявка з Facebook',
        body: 'Лід з форми по гардеробній кімнаті.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-06-20T08:33:00.000Z',
      },
      {
        id: 'evt-1005-rescheduled',
        type: 'visit_rescheduled',
        title: 'Візит перенесено',
        body: 'Нова дата: 10 липня, 10:00. Причина: відрядження клієнта.',
        actorId: 'emp-kyiv-2',
        occurredAt: '2026-07-02T12:30:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1006',
    name: 'Pawel Lewandowski',
    phone: '+48 730 201 445',
    email: 'pawel.lewandowski@example.com',
    leadStatus: 'in_progress',
    workflowStatus: 'visit_completed',
    officeCode: 'warsaw',
    source: 'office',
    sourceCreatedAt: '2026-06-12T14:10:00.000Z',
    initialMessage: 'Клієнт прийшов після рекомендації.',
    cityRegion: 'Warszawa, Srodmiescie',
    productInterest: 'Вбудовані шафи',
    estimatedBudget: 17500,
    assignedToId: 'emp-warsaw-3',
    firstManagerId: 'emp-warsaw-3',
    firstCall: {
      date: '2026-06-12T14:20:00.000Z',
      result: 'Візит відбувся',
      comment: 'Клієнт прийшов у салон того ж дня.',
    },
    visit: {
      status: 'completed',
      scheduledAt: '2026-06-12T15:30:00.000Z',
      completedAt: '2026-06-12T16:45:00.000Z',
      comment: 'Залишив розміри, очікує попередню оцінку.',
    },
    close: null,
    contract: null,
    callbackDueAt: '2026-07-08T14:00:00.000Z',
    lastComment: 'Підготувати попередній розрахунок.',
    lastActivityAt: '2026-06-12T16:45:00.000Z',
    attachments: [
      {
        id: 'att-1006-sketch',
        name: 'wardrobe-sketch.jpg',
        sizeLabel: '840 KB',
        addedAt: '2026-06-12T16:42:00.000Z',
      },
    ],
    events: [
      {
        id: 'evt-1006-created',
        type: 'created',
        title: 'Ручна заявка',
        body: 'Клієнт прийшов у салон після рекомендації.',
        actorId: 'emp-warsaw-3',
        occurredAt: '2026-06-12T14:10:00.000Z',
      },
      {
        id: 'evt-1006-completed',
        type: 'visit_completed',
        title: 'Візит відбувся',
        body: 'Залишив розміри, очікує попередню оцінку.',
        actorId: 'emp-warsaw-3',
        occurredAt: '2026-06-12T16:45:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1007',
    name: 'Катерина Савчук',
    phone: '+380 68 901 77 30',
    email: 'kateryna.s@example.com',
    leadStatus: 'converted',
    workflowStatus: 'successful',
    officeCode: 'kyiv',
    source: 'website',
    sourceCreatedAt: '2026-06-05T10:21:00.000Z',
    initialMessage: 'Потрібна кухня для новобудови, ремонт завершується.',
    cityRegion: 'Київ, Осокорки',
    productInterest: 'Кухня преміум',
    estimatedBudget: 31000,
    assignedToId: 'emp-kyiv-1',
    firstManagerId: 'emp-kyiv-1',
    firstCall: {
      date: '2026-06-05T10:50:00.000Z',
      result: 'Клієнт зацікавлений',
      comment: 'Планує швидке рішення, бюджет підтверджено.',
    },
    visit: {
      status: 'completed',
      scheduledAt: '2026-06-07T11:00:00.000Z',
      completedAt: '2026-06-07T12:10:00.000Z',
      comment: 'Обрали матеріали й комплектацію.',
    },
    close: null,
    contract: {
      contractNumber: 'K-KY-2026-0618',
      amount: 29800,
      prepayment: 9000,
      comment: 'Підписано після уточнення технічного завдання.',
      signedAt: '2026-06-18T13:20:00.000Z',
    },
    callbackDueAt: null,
    lastComment: 'Договір підписано.',
    lastActivityAt: '2026-06-18T13:20:00.000Z',
    attachments: [
      {
        id: 'att-1007-contract',
        name: 'contract-K-KY-2026-0618.pdf',
        sizeLabel: '2.4 MB',
        addedAt: '2026-06-18T13:20:00.000Z',
      },
    ],
    events: [
      {
        id: 'evt-1007-created',
        type: 'created',
        title: 'Заявка з сайту',
        body: 'Клієнтка вказала бюджет і бажаний термін.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-06-05T10:21:00.000Z',
      },
      {
        id: 'evt-1007-success',
        type: 'successful',
        title: 'Договір заключений',
        body: 'K-KY-2026-0618 на суму 29 800 EUR.',
        actorId: 'emp-kyiv-1',
        occurredAt: '2026-06-18T13:20:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1008',
    name: 'Tomasz Grabowski',
    phone: '+48 790 908 111',
    email: null,
    leadStatus: 'failed',
    workflowStatus: 'closed',
    officeCode: 'warsaw',
    source: 'facebook',
    sourceCreatedAt: '2026-05-29T17:05:00.000Z',
    initialMessage: 'Szuka najtanszego rozwiazania do wynajmowanego mieszkania.',
    cityRegion: 'Warszawa, Praga',
    productInterest: 'Недорога кухня',
    estimatedBudget: 4500,
    assignedToId: 'emp-warsaw-1',
    firstManagerId: 'emp-warsaw-1',
    firstCall: {
      date: '2026-05-30T08:40:00.000Z',
      result: 'Не підходить бюджет',
      comment: 'Клієнт шукає значно дешевше рішення.',
    },
    visit: null,
    close: {
      reason: 'expensive',
      comment: 'Після пояснення бюджету клієнт відмовився.',
      closedAt: '2026-05-30T09:05:00.000Z',
      actorId: 'emp-warsaw-1',
    },
    contract: null,
    callbackDueAt: null,
    lastComment: 'Закрито через бюджет.',
    lastActivityAt: '2026-05-30T09:05:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1008-created',
        type: 'created',
        title: 'Заявка з Facebook',
        body: 'Клієнт шукав бюджетне рішення.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-05-29T17:05:00.000Z',
      },
      {
        id: 'evt-1008-closed',
        type: 'closed',
        title: 'Лід закрито',
        body: 'Причина: дорого. Після пояснення бюджету клієнт відмовився.',
        actorId: 'emp-warsaw-1',
        occurredAt: '2026-05-30T09:05:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1009',
    name: 'Вікторія Дуб',
    phone: '+380 97 600 12 85',
    email: 'victoria.dub@example.com',
    leadStatus: 'failed',
    workflowStatus: 'closed',
    officeCode: 'kyiv',
    source: 'website',
    sourceCreatedAt: '2026-04-18T13:45:00.000Z',
    initialMessage: 'Потрібна консультація, але клієнт не відповідає.',
    cityRegion: 'Львів',
    productInterest: 'Кухня',
    estimatedBudget: null,
    assignedToId: 'emp-kyiv-2',
    firstManagerId: 'emp-kyiv-2',
    firstCall: null,
    visit: null,
    close: {
      reason: 'no_contact',
      comment: 'Три спроби контакту без відповіді.',
      closedAt: '2026-04-21T10:00:00.000Z',
      actorId: 'emp-kyiv-2',
    },
    contract: null,
    callbackDueAt: null,
    lastComment: 'Закрито після трьох спроб контакту.',
    lastActivityAt: '2026-04-21T10:00:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1009-created',
        type: 'created',
        title: 'Заявка з сайту',
        body: 'Клієнтка залишила телефон і email.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2026-04-18T13:45:00.000Z',
      },
      {
        id: 'evt-1009-closed',
        type: 'closed',
        title: 'Лід закрито',
        body: 'Причина: немає контакту. Три спроби без відповіді.',
        actorId: 'emp-kyiv-2',
        occurredAt: '2026-04-21T10:00:00.000Z',
      },
    ],
  },
  {
    id: 'lead-1010',
    name: 'Michael Brown',
    phone: '+48 664 118 532',
    email: 'michael.brown@example.com',
    leadStatus: 'new',
    workflowStatus: 'new',
    officeCode: 'warsaw',
    source: 'website',
    sourceCreatedAt: '2025-12-16T16:15:00.000Z',
    initialMessage: 'Looking for an English-speaking consultation for built-in furniture.',
    cityRegion: 'Warszawa, Wilanow',
    productInterest: 'Built-in storage',
    estimatedBudget: 14000,
    assignedToId: null,
    firstManagerId: null,
    firstCall: null,
    visit: null,
    close: null,
    contract: null,
    callbackDueAt: null,
    lastComment: null,
    lastActivityAt: '2025-12-16T16:15:00.000Z',
    attachments: [],
    events: [
      {
        id: 'evt-1010-created',
        type: 'created',
        title: 'Заявка з сайту',
        body: 'Клієнт просить консультацію англійською.',
        actorId: CRM_MOCK_ACTOR_ID,
        occurredAt: '2025-12-16T16:15:00.000Z',
      },
    ],
  },
];
