#!/usr/bin/env bash
# Serves the CRM on :4202 against the local Supabase stack and local API
# (../kolss-platform-api: `supabase start` + `scripts/dev-local.sh`).
# Writes its own gitignored environment.stack.ts, so a normal `npm start`
# (environment.local.ts) keeps working side by side.
set -euo pipefail
cd "$(dirname "$0")/.."

status="$(cd ../kolss-platform-api && supabase status -o env 2>/dev/null)" || {
  echo "Local Supabase is not running. Run 'supabase start' in ../kolss-platform-api" >&2
  exit 1
}
value() { printf '%s\n' "$status" | sed -n "s/^$1=\"\{0,1\}\([^\"]*\)\"\{0,1\}$/\1/p"; }

# SupabaseService treats http://127.0.0.1:54321 as its "not configured"
# placeholder, so address the same local Auth via localhost.
supabase_url="$(value API_URL | sed 's#//127\.0\.0\.1:#//localhost:#')"

cat > src/environments/environment.stack.ts <<TS
// Generated by scripts/start-local-stack.sh — local Supabase stack only.
export const environment = {
  production: false,
  supabaseUrl: '${supabase_url}',
  supabaseAnonKey: '$(value ANON_KEY)',
  apiBaseUrl: 'http://localhost:8080',
  siteUrl: 'http://localhost:4202',
  siteUrlPublic: 'http://localhost:4202',
};
TS

exec npx ng serve --configuration local-stack --port 4202
