import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envLocalPath = resolve(root, '.env.local');

const mode = process.argv.includes('--prod') ? 'prod' : 'local';

const fallbacks = {
  local: {
    supabaseUrl: 'http://127.0.0.1:54321',
    supabaseAnonKey: 'prototype-anon-key',
    siteUrl: 'http://localhost:4200',
    siteUrlPublic: 'http://localhost:4200',
  },
  prod: {
    supabaseUrl: '',
    supabaseAnonKey: '',
    siteUrl: 'https://crm.kolss.com',
    siteUrlPublic: 'https://crm.kolss.com',
  },
};

function parseEnvFile(path) {
  if (!existsSync(path)) return {};

  return Object.fromEntries(
    readFileSync(path, 'utf8')
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter((line) => line && !line.startsWith('#') && line.includes('='))
      .map((line) => {
        const separatorIndex = line.indexOf('=');
        const key = line.slice(0, separatorIndex).trim();
        const rawValue = line.slice(separatorIndex + 1).trim();
        const value = rawValue.replace(/^['"]|['"]$/g, '');
        return [key, value];
      }),
  );
}

function pick(sources, keys, fallbackValue) {
  for (const source of sources) {
    for (const key of keys) {
      const value = source[key]?.trim();
      if (value) return value;
    }
  }
  return fallbackValue;
}

function vercelSiteUrl() {
  const url = process.env.VERCEL_URL?.trim();
  return url ? `https://${url}` : '';
}

const fileEnv = parseEnvFile(envLocalPath);
// process.env wins (Vercel / CI); .env.local is a local fallback.
const sources = [process.env, fileEnv];
const fallback = fallbacks[mode];
const vercelUrl = vercelSiteUrl();

const environment = {
  production: mode === 'prod',
  supabaseUrl: pick(
    sources,
    ['SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_URL'],
    fallback.supabaseUrl,
  ),
  supabaseAnonKey: pick(
    sources,
    ['SUPABASE_ANON_KEY', 'NEXT_PUBLIC_SUPABASE_ANON_KEY'],
    fallback.supabaseAnonKey,
  ),
  siteUrl: pick(
    sources,
    ['SITE_URL', 'NEXT_PUBLIC_SITE_URL'],
    vercelUrl || fallback.siteUrl,
  ),
  siteUrlPublic: pick(
    sources,
    ['SITE_URL_PUBLIC', 'NEXT_PUBLIC_SITE_URL_PUBLIC'],
    vercelUrl || fallback.siteUrlPublic,
  ),
};

if (mode === 'prod') {
  const missing = [];
  if (!environment.supabaseUrl) missing.push('SUPABASE_URL');
  if (!environment.supabaseAnonKey) missing.push('SUPABASE_ANON_KEY');
  if (missing.length) {
    console.error(
      `sync-env --prod: missing required env: ${missing.join(', ')}\n` +
        'Set them in Vercel → Project → Settings → Environment Variables\n' +
        '(aliases NEXT_PUBLIC_SUPABASE_URL / NEXT_PUBLIC_SUPABASE_ANON_KEY also work).',
    );
    process.exit(1);
  }
}

const outputName =
  mode === 'prod' ? 'environment.prod.ts' : 'environment.local.ts';
const outputPath = resolve(root, 'src/environments', outputName);

const contents = `// Generated by scripts/sync-env.mjs (${mode}).
// Do not edit by hand — set env vars or .env.local instead.
export const environment = ${JSON.stringify(environment, null, 2)};
`;

writeFileSync(outputPath, contents);
console.log(`Generated src/environments/${outputName} (${mode})`);
